
GET http://localhost:3000/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGUiOiIwOTMwNDI2MzI5MiIsInN1YiI6MSwiZGlzcGxheV9uYW1lIjoicmFqYWJpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzY5NTg0NjgsImV4cCI6MTc3NzA0NDg2OH0.1mqEypHwuEMUy5imeFDtzDNciErJ4wkpDG2C0sNRILc

###
GET http://localhost:3000/addresses/1
Content-Type: application/json



###
POST http://localhost:3000/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGUiOiIwOTE4Mzc0NDY1OCIsInN1YiI6MywiZGlzcGxheV9uYW1lIjoiYWhtYWRpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzMwMDIyNDAsImV4cCI6MTc3MzA4ODY0MH0.jAADcGsjOzkVUnr98nvoBq0tV6nd6xlrQZPJHRBlwCw

{
  "privince":"aassdfdryan",
  "city":"asdasdasdfsd",
  "address":"arasdfsdasdyan",
  "postal_code":"1244567890",
  "reciver_mobile":"09183744658",
  "user_id":3
}
###
PATCH  http://localhost:3000/addresses/1
Content-Type: application/json

{
  "privince":"kurdestan",
  "city":"saghez",
  "address":"saghez"
}



###
DELETE   http://localhost:3000/addresses/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGUiOiIwOTE4Mzc0NDY1OCIsInN1YiI6MywiZGlzcGxheV9uYW1lIjoiYWhtYWRpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzMwMDIyNDAsImV4cCI6MTc3MzA4ODY0MH0.jAADcGsjOzkVUnr98nvoBq0tV6nd6xlrQZPJHRBlwCw

