###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "mobile":"09304263292",
  "name":"ali",
  "display_name":"rajabi",
  "password":"12345678"
}



###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "mobile":"09183744658",
    "password":"12345678"
}