
GET http://localhost:3000/categories


###
GET http://localhost:3000/categories/2
Content-Type: application/json



###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "title":"new cat5",
  "description":"category5 description"
}
###
PATCH  http://localhost:3000/categories/1
Content-Type: application/json

{
  "privince":"kurdestan",
  "city":"saghez",
  "address":"saghez"
}



###
DELETE   http://localhost:3000/categories/1
Content-Type: application/json

###
DELETE   http://localhost:3000/categories/safeRemove/2
Content-Type: application/json


###
DELETE   http://localhost:3000/categories/hardRemove/3
Content-Type: application/json
