
GET http://localhost:3000/orders


###
GET http://localhost:3000/orders/1
Content-Type: application/json



###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "userId":1,
  "status":"PENDING",
  "addressId":1,
  "total_amount":12354321,
  "orderItems":[{
    "productId":6,
    "quantity":2    
  },{
    "productId":9,
    "quantity":1    
  }]
}


###
PATCH  http://localhost:3000/orders/1
Content-Type: application/json

{
  "privince":"kurdestan",
  "city":"saghez",
  "address":"saghez"
}



###
DELETE   http://localhost:3000/orders/1
Content-Type: application/json

###
POST http://localhost:3000/orders/start-payment
Content-Type: application/json

{
  "orderId":2
}
  
###
POST http://localhost:3000/orders/verify-payment
Content-Type: application/json

{
  "trackId":4482764573,
  "orderId":2
}
  