
GET http://localhost:3000/products


###
GET http://localhost:3000/products/3
Content-Type: application/json



###
POST http://localhost:3000/products
Content-Type: application/json

{
  "title":"aryan product",
  "price":50000,
  "description":"product description",
  "categoryIds":[ 4,5 ],
  "stock":100
}
###
PATCH  http://localhost:3000/products/3
Content-Type: application/json

{
  "title":"aryan product",
  "price":60000,
  "description":"product description",
  "categoryIds":[4],
  "stock":100
}



###
DELETE   http://localhost:3000/products/1
Content-Type: application/json


###
POST http://localhost:3000/products/bookmark-product
Content-Type: application/json  

{
  "userId": 1,
  "productId": 3
}



###
POST http://localhost:3000/products/add-basket-item
Content-Type: application/json  

{
  "userId": 1,
  "productId": 4
}


###
POST http://localhost:3000/products/remove-basket-item
Content-Type: application/json  

{
  "userId": 1,
  "productId": 4
}