
GET http://localhost:3000/tickets


###
GET http://localhost:3000/tickets/2
Content-Type: application/json



###
POST http://localhost:3000/tickets
Content-Type: application/json

{
  "title":"new ticket",
  "subject":"ahmad abad",
  "description":"ticket description",
  "userId":2,
  "replyTo":2
}
###
PATCH  http://localhost:3000/tickets/1
Content-Type: application/json

{
  "privince":"kurdestan",
  "city":"saghez",
  "address":"saghez"
}



###
DELETE   http://localhost:3000/tickets/1
Content-Type: application/json
